### ISSUE TITLE
Update the HTML drafts for C++11, C++14 and C++17

### ISSUE THREAD

**Issue by Rakete1111** [timsong-cpp/cppwp#2]
Currently only the trunk version uses the updated cxxdraft-htmlgen that does syntax highlighting and is generally nicer to look at IMO. Compare:

- [Eelis version](http://eel.is/c++draft/dcl.dcl#dcl.stc-7) / [cppwp trunk](https://timsong-cpp.github.io/cppwp/dcl.dcl#dcl.stc-7)
- [C++11](https://timsong-cpp.github.io/cppwp/n3337/dcl.dcl#dcl.stc-9)
- [C++14](https://timsong-cpp.github.io/cppwp/n4140/dcl.dcl#dcl.stc-8)
- [C++17](https://timsong-cpp.github.io/cppwp/n4659/dcl.dcl#dcl.stc-7)

Is it possible to update them?

**Comment by timsong-cpp** [comment]
cxxdraft-htmlgen is tailored to the current standard sources and makes no effort to maintain compatibility with old ones. It's unlikely to work on the old sources without extensive patching.

**Comment by Rakete1111** [comment]
Okay, that's fine. Thanks :)
