### ISSUE TITLE
Current working draft is not current.

### ISSUE THREAD

**Issue by NicolBolas** [timsong-cpp/cppwp#3]
The [current working draft](https://timsong-cpp.github.io/cppwp/) is dated from 9/30/19. However, the actual current working draft *paper* ([N4835](http://www.open-std.org/JTC1/SC22/WG21/docs/papers/2019/n4835.pdf) ) is dated from 10/08/19.

This causes some things to be different between them. For example, [expr.prim.id]/3 defines when the names of immediate functions can be used. The [September draft states](https://timsong-cpp.github.io/cppwp/expr.prim.id#3):

> An id-expression that denotes an immediate function ([dcl.constexpr]) shall appear as a subexpression of an immediate invocation or in an immediate function context ([expr.const]).

While the October draft has more updated wording:

> An id-expression that denotes an immediate function (9.2.5) shall appear only
> - (3.1) as a subexpression of an immediate invocation, or
> - (3.2) in an immediate function context (7.7)

The difference is small, but it is there. In particular, the word "only" appears in the latter one (it's probably not strictly necessary, as "shall appear" ought to be good enough, but they felt the need to add it).

**Comment by timsong-cpp** [comment]
Updated to current master. Note that this post-dates N4835.
