### ISSUE TITLE
Add human-readable aliases for different draft versions

### ISSUE THREAD

**Issue by tocic** [timsong-cpp/cppwp#6]
Is it possible to add human-readable aliases like https://wg21.link/stdXX?

E.g., https://timsong-cpp.github.io/cppwp/cpp11 for https://timsong-cpp.github.io/cppwp/n3337.

**Comment by tocic** [comment]
@timsong-cpp What do you think about this? I think it's useful for e.g. SO answers, when you want to reference different versions of the standard and don't want to remember their document numbers.

**Comment by timsong-cpp** [comment]
Fixed in 220b0cbcdfa5cecd74a7119a513906a5caaf1560
